### ISSUE TITLE
var i in inner for loop

### ISSUE THREAD

**Issue by doowb** [substack/accountdown#4]
I have a setup where I was using two different `login` types to create a new account and it seemed to be working, but when I went to refactor, I noticed the second login type wasn't being used. I didn't update node or any dependencies, so I'm assuming I had something set up differently before.

It looks like the [inner for loop](https://github.com/substack/accountdown/blob/master/index.js#L59-L64) is reusing `i` and it's causing it to skip over the second login type.

I thought that the second `i` would be scoped properly, but it seems to be leaking into the outer for loop scope. I changed it to `j` and everything works.

Should I submit a PR for this or could there be something weird with my version of node? I'm using OS X v10.9.5 and node v0.10.29.

**Comment by substack** [comment]
Thanks for the issue! All fixed in 3.0.1.

**Comment by doowb** [comment]
Thanks!
